### ISSUE TITLE
QSPI Issue with ZX5-7030 (BOOT.bin to big)

### ISSUE THREAD

**Issue by magnifikus** [enclustra-bsp/enclustra-buildscripts#1]
Due to resulting BOOT.bin size after running bootgen from SDK of 6421 Kbyte the memory map for the QSPI flash is not working

Boot image 0x0 0x600000
Linux kernel 0x600000 0x500000

So when uploading the kernel parts of the boot image is overwritten.

Suggestion: fix the mercury offsets:

/\* QSPI Flash Memory Map */
# define QSPI_BOOT_OFFSET          0x00000000   // Storage for Bootimage (FSBL, FPGA Bitstream, UBoot)
# define QSPI_BOOT_SIZE            0x00700000   // size 7MB
# define QSPI_RESCUELINUX_OFFSET   0x00700000   // Storage for Linux Kernel
# define QSPI_RESCUELINUX_SIZE     0x00500000   // size 5MB
# define QSPI_RESCUEDTB_OFFSET     0x00C00000   // Storage for Linux Devicetree
# define QSPI_RESCUEDTB_SIZE       0x00080000   // size 512kB
# define QSPI_BOOTARGS_OFFSET      0x00C80000   // Storage for Uboot Environment
# define QSPI_BOOTARGS_SIZE        0x00080000   // size 512kB
# define QSPI_BOOTSCRIPT_OFFSET    0x00D00000   // Storage for Uboot boot script
# define QSPI_BOOTSCRIPT_SIZE      0x00040000   // size 256kB
# define QSPI_RESCUEROOTFS_OFFSET  0x00D40000   // Storage for Linux Root FS
# define QSPI_RESCUEROOTFS_SIZE    0x003C0000   // size 3.84MB

**Comment by sven-huerlimann** [comment]
Autsch!.. thanks. Will be fixed asap. 

Can't promise the fix will make it into the beta tomorrow, but we're on it.

TODO: switch to 64Mb Layout for the ZX5 and ZX1 (probably)

**Comment by kgugala** [comment]
Thanks for the bug report. Mercury board config has been updated and now it uses 64MB QSPI flash layout, which assumes 7MB for boot.bin image.

**Comment by kgugala** [comment]
I think we can close this one.
