### ISSUE TITLE
Trying to run EBE 1.8 on Ubuntu 20.04.1 LTS and getting make errors

### ISSUE THREAD

**Issue by DNR1406** [enclustra-bsp/enclustra-buildscripts#17]
Has anybody encountered this problem before? Whenever I try to run the buildscript for the SA1 C6 I7 it can fetch the required repos but when it starts building Linux I get errors on make. 
This is one as an example:
ERROR: Error running make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- LOADADDR=0x8000 uImage -j9 for Linux

I already updated all the required packages but that doesn't seem to help.

Any help would be greatly appreciated.

See the build log below.
[build.log](https://github.com/enclustra-bsp/enclustra-buildscripts/files/5274476/build.log)

**Comment by tholzsche** [comment]
Seems to be a dependency issue. This should solve the problem:
`sudo apt-get install libssl-dev`

**Comment by DNR1406** [comment]
Thanks, this and updating buildroot helped for me.
