### ISSUE TITLE
[Feature Request] Simple custom IP peripheral example / pointers / tutorial

### ISSUE THREAD

**Issue by niklas88** [enclustra-bsp/enclustra-buildscripts#3]
Hi all,

after your awesomely quick response for the binaries download problem I've now got a bitstream booted that adds a very basic AXI connected LED blinking circuit via the packaged IP mechanism. 

I had to work around [this](http://www.xilinx.com/support/answers/66479.html) Vivado bug and it's a bit clumsy to change the reference design because the LEDs aren't exposed in the block design but now it works. That is I can set its blinking speed via a memory write either from a standlone application or with a slight modification of the FSBL (essentially just writing a single uint32_t to the AXI base address). With FSBL this works well even while booting Linux from the SD card.

However trying to do the same from Linux either by using the devmem utility or writing to /dev/mem with dd doesn't do anything. I suspect I somehow need to expose the right memory range explicitly via devicetree or something but I'm quite new at this and would love some pointers as I couldn't find any tutorial for custom non PetaLinux systems. 

Thanks Niklas

**Comment by niklas88** [comment]
Never mind the part about it not working from Linux, I had missed a 0 when writing down the address. That said, I think a tutorial/example with custom IP would be a worthwhile addition.

**Comment by tgorochowik** [comment]
Hello Niklas,

thanks for the suggestion. Nevertheless we think that such tutorials are too general to be put in the documentation of the build environment.

In this project we want to focus on building the necessary parts to get up and running, not on fpga development in general.

There are quite a few tutorials covering these types of issues on the internet, so I'm sure you will easily find what you need.
