### ISSUE TITLE
Branch 1.3: Direct build/fetch options -x and -b don't build

### ISSUE THREAD

**Issue by niklas88** [enclustra-bsp/enclustra-buildscripts#4]
To better see what's going on I set debug to true in Utils. Then running with the ncurses GUI the build tool calls make ((parallel-)build) commands e.g. for U-Boot and BusyBox. However running

```
./build.sh -d Mercury_ZX1/Mercury_PE1/MMC -x Linux -x U-Boot -x BusyBox
```

it shows "Building XXX" but no actual build commands get called, fetch however works. The same happens when using -b. On the other hand "postbuild.sh" does get called. 

Taking a quick look at target.py my guess would be that somehow the subtargets are not enabled.

**Comment by tgorochowik** [comment]
Hello Niklas,

thanks for the report.

It was indeed a bug which disabled all the subtargets when the build environment was invoked in command line mode.

Please check the latest changes and don't hesitate to ask if you have more questions.

Hope this helps.
