### ISSUE TITLE
curl fails to download if the requested page has moved to another location

### ISSUE THREAD

**Issue by j4munoz** [enclustra-bsp/enclustra-buildscripts#8]
```
INFO: Getting binary boot_files_15eg_2
+curl -O -z /bsp-xilinx/binaries/boot_files_15eg_2/mercury_xu1_pe1_15eg_2i.zip http://www.enclustra.com/binaries/enclustra-bsp/v1.8.1/refdes/mercury_xu1_pe1_15eg_2i.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
INFO: New version of mercury_xu1_pe1_15eg_2i.zip downloaded.
+curl -O http://www.enclustra.com/binaries/enclustra-bsp/v1.8.1/refdes/mercury_xu1_pe1_15eg_2i.zip.hash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
+sha256sum -c mercury_xu1_pe1_15eg_2i.zip.hash
sha256sum: mercury_xu1_pe1_15eg_2i.zip.hash: no properly formatted SHA256 checksum lines found
WARNING: File corrupted
ERROR: Error while downloading boot_files_15eg_2 binary
```

Looking at the downloaded file, I can see its size is 0 bytes. After a bit of research, I observe that the server is sending a redirect http response, and curl is not able to follow it unless a particular flag is set on the command:

> -L, --location (HTTP/HTTPS) If the server reports that the requested page has moved to a different location (indicated with a Location: header and a 3XX response code), this option will make curl redo the request on the new place. If used together with -i, --include or -I, --head, headers from all requested pages will be shown. When authentication is used, curl only sends its credentials to the initial host. If a redirect takes curl to a different host, it won't be able to intercept the user+password. See also --location-trusted on how to change this. You can limit the amount of redirects to follow by using the --max-redirs option. When curl follows a redirect and the request is not a plain GET (for example POST or PUT), it will do the following request with a GET if the HTTP response was 301, 302, or 303. If the response code was any other 3xx code, curl will re-send the following request using the same unmodified method.

Hence, in the file "target.py" it is necessary to replace the command "curl -O " with "curl **-L** -O ". 
```

@@@ -1126,7 -1126,7 +1126,7 @@@ class Target
                  continue
              # download binary
              binary_file = os.path.basename(self.binaries[binary]["uri"])
--            call = "curl -O "
++            call = "curl -L -O "
              if self.binaries[binary]["redownload"] is False:
                  call = call + "-z " + download_path + "/" + binary_file
              elif os.path.isfile(download_path + "/" + binary_file):
@@@ -1144,7 -1144,7 +1144,7 @@@
                                                   binary_file,
                                                   "downloaded.")
                          # download sum
--                        call = "curl -O "
++                        call = "curl -L -O "
                          call = call + self.binaries[binary]["uri"] + ".hash"
                          self.utils.call_tool(call)
                          # check the checksum
```

**Comment by tgorochowik** [comment]
Hello @j4munoz 

Thank you for the report and for the detailed analysis!
This was happening because all the http links were redirected to https.

This has been fixed by disabling the redirection for the BSP files, but we will still apply the patch you suggest to prevent it from happening in the future.

Thanks!

**Comment by j4munoz** [comment]
No problem, I'm glad to help :)
Thank you!
